apiVersion: v1
kind: Deployment
metadata:
  name: deployteste
spec:
  selector:
    matchLabels:
      app: deploy
  replicas: 1 
  template: 
    metadata:
      labels:
        app: deploy
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 3333
